name: AutomaticAds BUILD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_NUMBER: ${{ github.run_number }}
  PROJECT_PATH: "AutomaticAds.csproj"
  PROJECT_NAME: "AutomaticAds-CS2"
  OUTPUT_PATH: "./AutomaticAds"

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore
      run: dotnet restore
    - name: Build
      run: dotnet build ${{ env.PROJECT_PATH }} -c WeaponPaints -o ${{ env.OUTPUT_PATH }}

  publish:
    if: github.event_name == 'push'
    permissions: write-all
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore
      run: dotnet restore
    - name: Build
      run: dotnet build ${{ env.PROJECT_PATH }} -c WeaponPaints -o ${{ env.OUTPUT_PATH }}
    - name: Zip
      run: |
        cd ${{ env.OUTPUT_PATH }}
        # Crear el zip con los archivos de la compilaci√≥n
        zip -r ../${{ env.PROJECT_NAME }}.zip .
        fi
    - name: AutomaticAds
      uses: ncipollo/release-action@v1.12.0
      with:
        artifacts: "${{ env.PROJECT_NAME }}.zip"
        name: "AutomaticAds v${{ env.BUILD_NUMBER }}"
        tag: "build-${{ env.BUILD_NUMBER }}"
        body: |
          Place the plugin in csgo/addons/counterstrikesharp/plugins/AutomaticAds
          After the first server startup, the configuration file will be created in csgo/addons/counterstrikesharp/configs/plugins/AutomaticAds
